CREATE TABLE IF NOT EXISTS "sessions" (
 "Session Name" VARCHAR NOT NULL,
 "Session ID" VARCHAR PRIMARY KEY,
 "Creator" VARCHAR NOT NULL,
 "Creator ID" VARCHAR NOT NULL,
 "Email" VARCHAR,
 "Folder Name" VARCHAR NOT NULL,
 "Folder ID" VARCHAR NOT NULL,
 "Start Time" TIMESTAMP,
 "Last Time Edited" TIMESTAMP,
 "Last Approval Action" VARCHAR,
 "Last Approval Time" TIMESTAMP,
 "Last Approver Name" VARCHAR,
 "Last Approver Id" VARCHAR,
 "Session Length" FLOAT NOT NULL,
 "Stream Count" FLOAT NOT NULL,
 "Stream Source" VARCHAR NOT NULL,
 "Rating Count" FLOAT NOT NULL,
 "Average Rating" FLOAT,
 "Root Folder (Level 0)" VARCHAR,
 "Subfolder (Level 1)" VARCHAR,
 "Subfolder (Level 2)" VARCHAR,
 "Subfolder (Level 3)" VARCHAR,
 "Subfolder (Level 4)" VARCHAR,
 "Views and Downloads" FLOAT NOT NULL DEFAULT 0,
 "Unique Viewers" FLOAT NOT NULL DEFAULT 0,
 "Minutes Delivered" FLOAT NOT NULL DEFAULT 0,
 "Average Minutes Delivered" FLOAT NOT NULL DEFAULT 0,
 "Most Recent View Date" TIMESTAMP
);
